### ISSUE TITLE
Migrations?

### ISSUE THREAD

**Issue by srfoster** [Bogdanp/deta#10]
What's the current story for doing a migration -- e.g. adding a column to an existing table?  I didn't see functions for this.  Is that a "use raw SQL" kind of thing?

**Comment by Bogdanp** [comment]
> Is that a "use raw SQL" kind of thing?

Yep. It's a "use [my other library](https://docs.racket-lang.org/north/index.html?q=north) in conjunction with raw SQL" kind of thing.

**Comment by srfoster** [comment]
Awesome!  I didn't expect you to have another library up your sleeve for that. :)
