### ISSUE TITLE
Intolerance of non-integer primary keys

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/deta#11]
If I try to make a schema with a non-integer primary key, I get an error:

```racket
#lang racket/base

(require deta db)

(define-schema article
  ([page symbol/f #:primary-key]
   [date string/f]))

(define cache-conn (sqlite3-connect #:database "db.sqlite" #:mode 'create))

(create-table! cache-conn 'article)

(define a (make-article #:page 'my-article.html
                        #:date "2020-01-04"))

(insert-one! cache-conn a)
```

results in this error (on the `insert-one!` call):

```
set-article-page: contract violation
  expected: symbol?
  given: 1
  in: an and/c case of
      the 2nd argument of
      (->*
       (article? (and/c symbol? any/c))
       (boolean?)
       article?)
  contract from: (function set-article-page)
  blaming: /Users/joel/Documents/code/sandbox/deta/deta-1.rkt
   (assuming the contract is correct)
  at: /Users/joel/Documents/code/sandbox/deta/deta-1.rkt
```

**Comment by Bogdanp** [comment]
I think the fix here would be to make [this code](https://github.com/Bogdanp/deta/blob/56f0eb108a8f4c4f73ea021a9823557c5d4a0c87/deta-lib/query.rkt#L90-L105) deal with cases where `pk` is already set to a value and, possibly, error when it isn't and its type is not an integer.

**Comment by otherjoel** [comment]
Looks like the problem is SQLite-specific. Its `dialect-supports-returning?` is `#f` and its `(dialect-last-id-query dialect)` is always going to return the automatically-created `rowid` column regardless of what the primary key column is.
