### ISSUE TITLE
Union generates parens that break queries on SQLite

### ISSUE THREAD

**Issue by otherjoel** [Bogdanp/deta#15]
Using the example for `union` from the docs:

```racket
#lang racket/base
(require racket/base deta threading db)

(define cache-conn (sqlite3-connect #:database "test.db" #:mode 'create))

(define q
  (~> (select _ 1)
      (union (select _ 2))
      (union (select _ 3))))
(displayln q)
(lookup cache-conn q)
```

Produces:

```
#<query: SELECT 1 UNION (SELECT 2 UNION (SELECT 3))>
. . prepare: near "(": syntax error
  error code: 1
```

Running the generated query directly in a SQLite client produces the same error. Removing all parentheses allows the query to run fine.

Maybe the parentheses are something PostgreSQL tolerates for readability but SQLite prohibits? See https://stackoverflow.com/a/4653180

**Comment by Bogdanp** [comment]
Thanks! I had no idea this was not standard. For now, I've special-cased the SQLite dialect so it doesn't emit parens, which should fix this problem.

**Comment by otherjoel** [comment]
Thank you!
