### ISSUE TITLE
SQLite incompatibility with the use of (DATE '1995-01-01') in SQL statements

### ISSUE THREAD

**Issue by hovege** [Bogdanp/deta#21]
Following the tutorial, I stumbled upon the following problem.

```
racket@books.rkt> (for/list ([b (in-entities conn (~> (from book #:as b)
                                      (where (< b.published-on (date "1955-01-01")))
                                      (order-by ([b.published-on #:desc]))))])
    (book-title b))
prepare: near "'1955-01-01'": syntax error
  error code: 1
```

The problem seems to be that the SQL statement built

```
racket@books.rkt> (displayln (~> (from book #:as b)
                                      (where (< b.published-on (date "1955-01-01")))
                                      (order-by ([b.published-on #:desc]))))
#<query: SELECT b.id, b.title, b.author, b.published_on FROM books AS b WHERE b.published_on < (DATE '1955-01-01') ORDER BY b.published_on DESC>
```

It seems incompatible with SQLite version 3.31.1.

```
racket@books.rkt> (query-list conn "select sqlite_version()")
'("3.31.1")
```

If we change the SQL to 

`SELECT b.id, b.title, b.author, b.published_on FROM books AS b WHERE b.published_on < DATE('1955-01-01') ORDER BY b.published_on DESC
`

then it works on version 3.31.1.  That's the issue.  Thanks for writing the library!

**Comment by Bogdanp** [comment]
This is now fixed, but it's worth noting that the `date` function and its siblings works differently in SQLite than in Postgres. So the query in your example still won't work w/o modification. See [this document](https://sqlite.org/lang_datefunc.html) for details.
