### ISSUE TITLE
Postgresql binary type support

### ISSUE THREAD

**Issue by tfidfwastaken** [Bogdanp/deta#26]
Currently `deta` maps `binary/f` fields to the type `BLOB`. But in Postgresql, no such type actually exists, hence creating a table with a `binary/f` field gives me:
```
query-exec: type "blob" does not exist
  SQLSTATE: 42704
```
From the Postgresql wiki:
> Caveat: many people come to this page looking for PostgreSQL's equivalent of the MySLQ (sic) "BLOB*" data types. The equivalent in Postgres is BYTEA.

I think the behaviour should be that `binary/f` should map to `BYTEA` for Postgresql.

**Comment by tfidfwastaken** [comment]
The problem seems to be over here:
https://github.com/Bogdanp/deta/blob/028094906100447844338d274543882d7e8ce58b/deta-lib/type.rkt#L128-L137

Changing it to:
```racket
(define-values (binary/f? binary/f)
  (let ()
    (struct binary-field ()
      #:methods gen:type
      [(define (type-contract _) bytes?)
       (define (type-declaration _ dialect)
         (match dialect
           ['sqlite3    "BLOB"]
           ['postgresql "BYTEA"]))
       (define (type-load _ dialect v) v)
       (define (type-dump _ dialect v) v)])
```
seems to have fixed it for me.

I would be glad to open a PR for this patch.

**Comment by Bogdanp** [comment]
> I would be glad to open a PR for this patch.

Please do!
