### ISSUE TITLE
Question: convey "where" conditions as values?

### ISSUE THREAD

**Issue by yurkobb** [Bogdanp/deta#32]
(I'm sorry if this is not the best place to ask questions; please point me to a more appropriate channel if so).

I'm wondering if it would be possible to somehow express "where" conditions as values that could be passed around. Let's say I have a function like:

```racket
(define (query-products-many lang #:extra-conditions [extra #f])
  ...)
```

And I would like for that function to be able to append additional conditions to its `WHERE` clause based on the `extra` argument. My intuition would be to be able to somehow pass a form like `(> products.price 50)` as a value to the function - is something like that possible?

**Comment by Bogdanp** [comment]
Normally, you'd have a function that produces the base query, then augment that query. For example:

```racket
(define (make-products-query)
  (select (from product #:as p) p.name))

(~> (make-products-query)
    (where (> p.price 100)))
```

But you can also do it by passing in a list of functions:

```racket
(define (query-products-many lang #:extras [extras null])
  (define q
   (for/fold ([q (where (from product #:as p) (= p.lang ,lang)]) 
             ([proc (in-list extras)])
    (proc q))
  (in-entities conn q))

(query-products-many "en" #:extra (list (lambda (q) (where q (> p.price 100))))
```

Applying `where` to a query multiple times implicitly `and`s the existing clause with the new clause. There is also `or-where`, which `or`s any existing clause with the new clause.

**Comment by yurkobb** [comment]
Thank you, that's useful!

(Is it okay to keep asking similar questions here or is it better to do elsewhere?)

**Comment by Bogdanp** [comment]
My pleasure! Asking questions here is absolutely fine.
