### ISSUE TITLE
Question / suggestion: "virtual" fields?

### ISSUE THREAD

**Issue by yurkobb** [Bogdanp/deta#35]
When modelling my data (entities translated in multiple languages) I'm gravitating towards something like the following:

```racket
(struct/contract thing/i18n
  ([lang string?]
   [title string?]
   [description string?]))

(struct/contract thing
  ([uuid uuid?]
   [sku string?]
   [price exact?]
   [i18n (listof thing/i18n)]))  ;; or possibly a hash of lang code -> thing/i18n
```

i.e. I would like to be working with `thing` mostly as a single entity in that I would like to be able to retrieve `thing` from the database as one logical operation (and one `join`ed query) as well delegate the job of `insert`ing its related tables to itself (perhaps via a hook).

I was thinking that if deta could allow me to declare additional struct fields that are not mapped directly to database columns, I could use hooks to insert the relevant data in the related tables and to somehow map `join`ed query results onto the additional fields.

I don't mean lazy behavior necessarily, but the ability to have a hybrid nonvirtual-virtual schema.

What do you think?

**Comment by Bogdanp** [comment]
Yes, I think this would be a good feature to have and it shouldn't be too hard to implement. Do you want to take a stab at it?

**Comment by yurkobb** [comment]
I would have to grasp macros and syntax-parse better first (a good thing to do anyway), but I would try.

I'm thinking also how it would look for the user to perform joins and extract more than one entity from a query result - `in-entities` wouldn't probably work for this. Maybe it would be good to have something that would allow creating an entity semi-manually from a selected set of columns of a query (perhaps by exposing [`make-entity-instance`](https://github.com/Bogdanp/deta/blob/master/deta-lib/query.rkt#L232) or something similar)?

**Comment by Bogdanp** [comment]
Ah, I hadn't thought much about the join use case. I think this should be done in two steps: first the virtual fields on their own and then adding functionality for how to hook in and fill those rows when querying. The first one can stand on its own while we figure out a nice way to do the second (or if we should in the first place).

For one-to-one relationships, the addition of virtual fields alone should be enough to enable things like:

```racket
(define-schema product
  #:table "products"
  ([uuid uuid/f]
   [sku string/f]
   [name #:virtual]))

(define (get-products-with-i18n conn lang)
  (in-entities 
    conn
    (~> (from product #:as p)
        (join "translations" #:as t #:on (= t.product-uuid p.uuid))
        (where (= t.lang ,lang))
        (select p.uuid p.sku t.name)
        (project-onto product-schema))))
```

For the one-to-many use case I think it might just be preferable to let the user run two queries and join the data themselves. I don't think something like the following is bad at all:

```racket

(define-schema product
  #:table "products"
  ([uuid uuid/f]
   [sku string/f]
   [(translations (hash)) #:virtual]))

(for*/sequence ([p (in-entities conn (from product #:as p))]
                [(lang name description) (in-rows conn (~> (from "translations" #:as t)
                                                           (where (= t.product-uuid ,(product-uuid p)))
                                                           (select t.lang t.name t.description)))])
  (update-product-translations p (lambda (translations)
                                   (hash-set translations lang (i18l name description)))))
```

**Comment by yurkobb** [comment]
> Ah, I hadn't thought much about the join use case. I think this should be done in two steps: first the virtual fields on their own and then adding functionality for how to hook in and fill those rows when querying. The first one can stand on its own while we figure out a nice way to do the second (or if we should in the first place).

Makes total sense.

> 
> For one-to-one relationships, the addition of virtual fields alone should be enough to enable things like:
>
> ```racket
> (define-schema product
>   #:table "products"
>   ([uuid uuid/f]
>    [sku string/f]
>    [name #:virtual]))
> 
> (define (get-products-with-i18n conn lang)
>   (in-entities 
>     conn
>     (~> (from product #:as p)
>         (join "translations" #:as t #:on (= t.product-uuid p.uuid))
>         (where (= t.lang ,lang))
>         (select p.uuid p.sku t.name)
>         (project-onto product-schema))))
> ```

Thanks for the example! I have a question: is `product-schema` an additional virtual schema in the example? Or it could potentially be also the original schema where `name` is a virtual field into which we explicitly "project" data by `select`ing it? 

> For the one-to-many use case I think it might just be preferable to let the user run two queries and join the data themselves. I don't think something like the following is bad at all:
> 
> ```racket
> (define-schema product
>   #:table "products"
>   ([uuid uuid/f]
>    [sku string/f]
>    [(translations (hash)) #:virtual]))
> 
> (for*/sequence ([p (in-entities conn (from product #:as p))]
>                 [(lang name description) (in-rows conn (~> (from "translations" #:as t)
>                                                            (where (= t.product-uuid ,(product-uuid p)))
>                                                            (select t.lang t.name t.description)))])
>   (update-product-translations p (lambda (translations)
>                                    (hash-set translations lang (i18l name description)))))
> ```
Fair point; and this is comparable to Django's `prefetch_related`. I think `deta` is more flexible here by staying close to SQL and thus allowing to the user manually "unpack" the one-to-many result set into desired data structures if needed (I've been looking at [`group-rows`](https://docs.racket-lang.org/db/query-api.html?q=db#%28def._%28%28lib._db%2Fbase..rkt%29._group-rows%29%29) from `db` for possible help).

**Comment by Bogdanp** [comment]
> Thanks for the example! I have a question: is product-schema an additional virtual schema in the example? Or it could potentially be also the original schema where name is a virtual field into which we explicitly "project" data by selecting it?

`product-schema` refers to the original schema in my example (`define-schema` introduces a `<name>-schema` binding for every defined schema) so the idea is indeed that we project selected data onto the virtual field.

**Comment by yurkobb** [comment]
Thanks for clarification!

I was reading the code and trying to think about how to approach implementing the virtual fields. I can see two general directions:

1. Add a `virtual` field to the [field struct](https://github.com/Bogdanp/deta/blob/master/deta-lib/private/field.rkt#L12); then add extra logic to exclude virtual fields anywhere they are being considered for/from SQL.
2. Add a separate `virtual-fields` field to the [schema struct](https://github.com/Bogdanp/deta/blob/master/deta-lib/private/schema.rkt#L13) and assign virtual fields there. Then add extra logic for `project-onto`.

While No. 1 was my initial plan, No. 2 starts to look like a better option for me now. What do you think?

**Comment by Bogdanp** [comment]
I'd go with variant 1 because `project-onto` is positional, not nominal so variant 2 would complicate construction, and I think it might make sense for project-onto to support regular structs down the line.

**Comment by yurkobb** [comment]
Thanks for feedback! I see. Alright then! I have already made some attempts at variant 1.

There is also a question of a default value for a virtual field - it is probably mandatory since otherwise the entity struct instance could not be created (the default may be `#f` if not provided otherwise). As for the other attributes, I think only `#:contract` makes sense for a virtual field.

**Comment by yurkobb** [comment]
...and I'm not sure about the `type:expr` - whether it is relevant; it may be relevant for `project-onto` but not otherwise; and if I want the virtual field to be something which doesn't correspond to a database type at all? Maybe they should be type-less and rely on the contract only.

**Comment by Bogdanp** [comment]
I think I would make setting a default for virtual fields mandatory for now (so only add `#:virtual` to the pattern with a default of the `fld` syntax class). We can always relax this later if it turns out that most of the time you just want `#f` as the default. I think `#:wrapper` also makes sense for these fields in addition to `#:contract`.

I'd make the type mandatory for now to keep the implementation simple, and to keep this close to how virtual schemas work. If necessary, we can add an `any/f` type for when one doesn't care about the type, but the type is necessary right now for `project-onto` to work right.

**Comment by yurkobb** [comment]
> I think I would make setting a default for virtual fields mandatory for now (so only add `#:virtual` to the pattern with a default of the `fld` syntax class).

I agree, and thanks for the hint!

> I think `#:wrapper` also makes sense for these fields in addition to `#:contract`.

Fair point.

> I'd make the type mandatory for now to keep the implementation simple, and to keep this close to how virtual schemas work. If necessary, we can add an `any/f` type for when one doesn't care about the type, but the type is necessary right now for `project-onto` to work right.

I'm thinking if I'll be able to utilize this for my initial use case - storing structs or lists (or hashes) of structs in these fields; for that I would need something like `any/f` anyway. Since such type doesn't make sense for non-virtual fields, it should raise an error when used on a normal field. Its behavior would then be:

- type-declaration: raise an error
- type-dump: raise an error
- type-load: simple pass-through from `db` to the user

And the user should be prevented from declaring it on a non-virtual field at all.

Sorry for all this theorizing; but I feel like I need to understand this well before attempting implementing it.

**Comment by Bogdanp** [comment]
> I'm thinking if I'll be able to utilize this for my initial use case - storing structs or lists (or hashes) of structs in these fields; for that I would need something like any/f anyway.

Ah, yep, I'd lost track of that in my last comment.  The behaviors you describe sound reasonable, but I wouldn't worry too much about 

    the user should be prevented from declaring it on a non-virtual field at all

if it turns out to be hairy to implement.

> Sorry for all this theorizing; but I feel like I need to understand this well before attempting implementing it.

No worries!  I enjoy the discussion.

**Comment by yurkobb** [comment]
Hi! Just FYI, my [current work-in-progress](https://github.com/yurkobb/deta/commits/feature/virtual-field) on this feature.

**Comment by Bogdanp** [comment]
Looks good!

**Comment by yurkobb** [comment]
Thanks! Just made [a change covering updates](https://github.com/yurkobb/deta/commit/202012a7919bea0d629685a40fdc75a60ae47e4e); there's one thing I am not 100% sure is safe - the removal of `entity-changed?` in favor of `meta-can-update?` only; as far as I can tell, they cover the same case (one checks the non-emptiness of meta-changes, the other checks the `'changed`meta-state); but there might be a subtlety here I don't yet understand.

**Comment by Bogdanp** [comment]
I went ahead and replied on the commit. I think it's safe to use `meta-can-update?` instead of `entity-changed?` and to drop the latter. I think it may have been left in by accident.
