### ISSUE TITLE
Question: polymorphic operations on entities?

### ISSUE THREAD

**Issue by yurkobb** [Bogdanp/deta#36]
Say, I have two schemas:

```racket
(define-schema first
  ([uuid uuid/f #:primary-key]
   [somefield string/f]))

(define-schema second
  ([uuid uuid/f #:primary-key]
   [foo (numeric/f 10 2)]))
```

I would like to write a function that would get the `uuid` of either. I could use `(struct->vector)` and `(vector-ref)` by index, but that seems hackish; we already have `(schema-fields ...)` in `deta/private/schema`, and we have `(field-id ...)` in `deta/private/field`. Maybe we could implement a function that would look up the field id in the schema and get its value from an entity by index?

Or is there a simple way I'm missing?

**Comment by yurkobb** [comment]
A more radical idea - implement (parts of) `gen:dict` on <s>schemas</s> entities :)

**Comment by Bogdanp** [comment]
`define-schema` can take arbitrary struct options, so I would use [generics](https://docs.racket-lang.org/reference/struct-generics.html?q=define-generics#%28form._%28%28lib._racket%2Fgeneric..rkt%29._define-generics%29%29) here:

```racket
#lang racket/base

(require deta racket/generic)

(define-generics uuid-provider
  [get-uuid uuid-provider])

(define-schema first
  ([uuid uuid/f #:primary-key]
   [somefield string/f])
  #:methods gen:uuid-provider
  [(define (get-uuid f)
     (first-uuid f))])

(define-schema second
  ([uuid uuid/f #:primary-key]
   [foo (numeric/f 10 2)])
  #:methods gen:uuid-provider
  [(define (get-uuid s)
     (second-uuid s))])

(get-uuid (make-first ...))
(get-uuid (make-second ...))
```

**Comment by yurkobb** [comment]
That's a useful suggestion, thank you! With this approach I can replace one of my macros with a plain function.

(I think I should close this and continue the broader discussion in #14).
