### ISSUE TITLE
jsonb operators

### ISSUE THREAD

**Issue by yurkobb** [Bogdanp/deta#47]
Ended up needing to do ~~crazy~~ convenient things like ordering by values inside jsonb fields :)

Something like `SELECT * FROM products ORDER BY attributes->'year'` or `SELECT * FROM products WHERE attributes->'year' = '2021'`.

Not sure how to make those look nice in s-expressions... perhaps analogous to `array-concat` and other `array/f` functions? Something like `json-ref`, etc, perhaps...

P.S. Sorry for editing, hit return while typing...

**Comment by Bogdanp** [comment]
Yup, I think we should just add text operators for those operations, but one thing I dislike about `array-concat` and friends is that they're recognized by symbol, not by binding so what I'd like to do is add a `deta/operators` module where you can import all of these special operators from and use them. That way you get completion and the ability to rename them, etc. I'll take a stab at that over the weekend.

**Comment by yurkobb** [comment]
Oh, that'd be amazing to have them as real bindings!

Thinking about the possible names for the [basic operators](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-JSON-OP-TABLE):

- `->` : `json-ref` / `json->`
- `->>` : `json-ref/convert` / `json->>`
- `#>` : `json-ref/path` / `json#>`
- `#>>` : `json-ref/path/convert` / `json#>>`

The `json->` style are shorter but potentially confusing...

The [additional operator](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) suggestions:
- `@>` : `json-contains?` or `json-contains-right?`
- `<@` : `json-contains-left?` (not sure whether those left/right variants even make sense in the s-exp world)
- `?` : `json-has-key?`
- `?|` : `json-has-key/any?`
- `?&` : `json-has-key/every?`
- `||` : `json-concat`
- `-` : `json-remove`
- `#-` : `json-remove/path`
- `@?` : `json-has-path?`
- `@@` : `json-path-check`

(Just ideas)

P.S. Really excited seeing all these new features in deta recently!
