### ISSUE TITLE
query-exec fails with queries that generate prepared statements

### ISSUE THREAD

**Issue by eko234** [Bogdanp/deta#50]
when you use unquote inside a query it generates a query with the following form:
`( query statement args ... )`
but at least when you run it with query exec using racket 8.0 it fails with this message:

```
prepare: near "AS": syntax error
  error code: 1
  context...:
   /usr/share/racket/collects/db/private/sqlite3/connection.rkt:466:0: handle-status*
   /usr/share/racket/collects/db/private/sqlite3/connection.rkt:422:8
   /usr/share/racket/collects/db/private/sqlite3/connection.rkt:225:4: prepare1* method in connection%
   /usr/share/racket/collects/db/private/generic/common.rkt:163:24
   /home/jujo/.racket/8.0/pkgs/deta-lib/private/query.rkt:28:2
   /usr/share/racket/collects/racket/contract/private/arrow-higher-order.rkt:375:33
   /usr/share/racket/collects/db/private/generic/functions.rkt:90:0: compose-statement
   /usr/share/racket/collects/db/private/generic/functions.rkt:148:0: query-exec
```

this happens even in your example file, the workaround is nothing fancy (pattern matching and using apply), but I don't think this is the expected behaviour. could it be something in my racket setup or do you find the same results using racket 8.0?

**Comment by Bogdanp** [comment]
The issue is likely that the version of SQLite on your system is from before they added support for the `AS` keyword in `DELETE` commands. Though I am confused about your fix, can you say more about it? Does the problem go away if you run `raco pkg install libsqlite3-x86_64-linux`?

**Comment by eko234** [comment]
@Bogdanp  I was eager about the fix, I haven't tried it out but if the problem is my sqlite version then I'm probably wrong about it, I will try out tomorrow and will let you know, thanks.

Edit: btw, I am running a update statement.

**Comment by Bogdanp** [comment]
I believe `UPDATE` had the same issue. Prior to some version, SQLite only allowed queries of the form `UPDATE foo f SET ...` and not `UPDATE foo AS f SET ...`, which is what deta generates. Same for `DELETE`.

**Comment by eko234** [comment]
well it worked, the thing is I need to distribute my application for windows machines, and I find there are two packages, one for linux and other for macos (the libsqlite package), I know maybe it is going out of the scope of this repo, but do you know of a way to work this out?

**Comment by eko234** [comment]
nevermind, I worked it out, in windows i downloaded the corresponding sqlite version for my machine and replaced racket's default dll in the lib directory, now it works well, thank you so much again.

**Comment by Bogdanp** [comment]
You're welcome! If I can find the time, I'll take a look at making a windows version of the sqlite package as well.

**Comment by Bogdanp** [comment]
I've added win32 packages for libsqlite3 as well as an amalgamation package which will automatically install the right package for a given platform so if you just make your app depend on `libsqlite3` you shouldn't need to manually replace the dll anymore and it should simplify distribution to other computers.
