### ISSUE TITLE
integer exceed default `type?` contract?

### ISSUE THREAD

**Issue by dannypsnl** [Bogdanp/deta#53]
When I'm using **deta** to create some schemas, I found some fields might have data in `int32?` but **deta** can only build `integer/f` which is `int4`.

I think exposing `define-type` would be the best solution for future extensive. For example

```racket
(define-type bigint
  #:contract exact-integer?
  #:declaration "BIGINT")
```

**Comment by Bogdanp** [comment]
It's not documented yet, but you can access `define-type` through `(submod deta/type define)`. I'm going to try to keep that interface stable, so it should be safe to use it if you're comfortable doing so without documentation.
