### ISSUE TITLE
WHERE column IN ...

### ISSUE THREAD

**Issue by yanyingwang** [Bogdanp/deta#6]
I already read the doc, but can not find a way to write a query may be like this SQL:
~~~sql
SELECT "users" FROM "users" WHERE "users"."id" IN (1, 2, 3)
~~~

The most approximate way would be like this:
~~~racket
> (~> (from user #:as u)
    (where (IN u.id '(1 2 3))))
(query "SELECT u.id, u.name FROM users AS c WHERE IN(u.id, QUOTE(1(2, 3)))")

~~~
but apparently, this doesn't work.

**Comment by Bogdanp** [comment]
`(where (in u.id  (list 1 2 3)))` should work (`in` is lowercase), although you're right that this isn't shown anywhere in  the docs. I'll fix that later this week. In the mean time, [this file](https://github.com/Bogdanp/deta/blob/c9294309718857aacf775d81d8cc74abcdac002e/deta-test/deta/sql-postgresql.rkt) contains many examples of deta queries and the SQL they map to so if you're ever stuck, that's a good place to check.
