### ISSUE TITLE
how to join and select column as array_agg with defined array/f schema

### ISSUE THREAD

**Issue by yanyingwang** [Bogdanp/deta#7]
Let's say I have two tables named `users` and `roles`, they are related by `roles_users` in the many-to-many relationships.

|users | roles_users | roles |
|--|--|--|
|:id       |    :id           | :id
|:name | :user_id   |  :name
|       |  :role_id   | 

And then now, I need to check out all the roles of each one user. The code may be like this:

~~~racket
(define-schema user-with-role
  #:virtual
  ([id id/f #:primary-key #:auto-increment]
   [name string/f]
   [role_names (array/f string/f)]))

(lookup conn (~> (from "users" #:as u)
                 (join "roles_users"
                       #:as ru
                       #:on (= ru.user_id u.id))
                 (join "roles"
                       #:as r
                       #:on (= ru.role_id r.id))
                 (select u.id u.name (as (array_agg r.name) role_names))
                 (group-by u.id)
                 (project-onto user-with-role-schema)))
~~~

The result was expected to be like `(user-with-role #<meta> 22 "Yanying" '#(role1 role2 role3))`, but instead of generating the defined schema format data, it raised a `in-vector: contract violation excepted: vector given: pg-array ...... [,bt for context]` error. This seems it didn't convert the pg-array type correctly.

Am I missing something and do we have a way to achieve this so far?

**Comment by Bogdanp** [comment]
Thanks for the report! This was a bug in how the library processed arrays and should now be fixed.
