### ISSUE TITLE
WHERE column NOT IN list

### ISSUE THREAD

**Issue by yanyingwang** [Bogdanp/deta#8]
I guess I find another bug:

~~~racket
> (~> (from "users" #:as u)
      (where (not (in u.id (list 1 2 3)))))

(query "SELECT * FROM users AS u WHERE NOT (u.id IN (1, 2, 3))")
>
>
~~~

it was expected to return `  "SELECT * FROM users AS u WHERE  u.id NOT IN (1, 2, 3)"`

----
A more practical example:
~~~racket
(~> (from "users" #:as u)
      (where (= u.name "Yanying"))
      (where (not (in u.id (list 11 22 33)))))
(query "SELECT * FROM users AS u WHERE (u.name = 'Yanying') AND (NOT (u.id IN (11, 22, 33)))")
~~~

**Comment by Bogdanp** [comment]
This was intentional, but maybe I misunderstood something  when I implemented this.

IIRC, `x NOT IN y` desugars into `NOT x IN y` so there should be no difference between the two.  Is there?

**Comment by yanyingwang** [comment]
Oh,  you're right, I get it wrong. At least this is not my original problem. I'll raise another issue if I found one. Thanks!
