### ISSUE TITLE
expression operator ANY (array expression)

### ISSUE THREAD

**Issue by yanyingwang** [Bogdanp/deta#9]
as [doc]( https://docs.racket-lang.org/db/sql-types.html?q=sql%20timestamp#%28part._postgresql-types%29) from `db-lib` says:

> A list may be provided for an array parameter, in which case it is automatically converted using list->pg-array. The type annotation can be dropped when the array type can be inferred from the left-hand side.

then we can write code like below:
~~~racket
>  (query-rows conn "SELECT * FROM users AS u WHERE u.email = ANY ($1)"
              (list->pg-array (list "1@1.com" "2@2.com")))
'()
>
~~~

But this cannot be converted correctly from `deta`:
~~~racket
>  (lookup conn
          (~> (from "users" #:as u)
              (where (= u.email (any ,(list "1@1.com" "2@2.com"))))))
; prepare: syntax error at or near "ANY"
;   SQLSTATE: 42601
; [,bt for context]
>
>
>  (~> (from "users" #:as u)
              (where (= u.email (any ,(list "1@1.com" "2@2.com")))))
(query
 "SELECT * FROM users AS u WHERE u.email = (ANY($1))"
 '("1@1.com" "2@2.com"))
>
>
~~~

**Comment by Bogdanp** [comment]
Thanks for reporting! This should be fixed now.
